"use client";

export const dynamic = 'force-dynamic';

import { useLanguage } from "@/lib/language-context";

export default function TermsPage() {
  const { t, lang } = useLanguage();
  const isRtl = lang === "ar";

  return (
    <div
      className="min-h-screen flex flex-col bg-brand-ink"
      dir={isRtl ? "rtl" : "ltr"}
    >
      {/* Header */}
      <header className="bg-brand-navy border-b border-white/[0.08] px-5 py-4">
        <div className="max-w-3xl mx-auto flex items-center gap-4">
          <div className="w-10 h-10 bg-brand-blue rounded-xl flex items-center justify-center text-white font-bold text-lg">W</div>
          <div>
            <p className="font-bold text-base leading-tight text-white">WAK Solutions</p>
            <p className="text-xs text-brand-slate">{t("termsPageTitle")}</p>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 w-full max-w-3xl mx-auto px-5 py-10 space-y-8">
        {/* Title block */}
        <div className="text-center space-y-1">
          <h1 className="text-3xl font-bold text-brand-blue">{t("termsPageTitle")}</h1>
          <p className="text-sm text-brand-slate">{t("termsPageLastUpdated")}</p>
        </div>

        {/* 1. Service Overview */}
        <Section title={t("termsPageSectionService")} isRtl={isRtl}>
          <p>
            WAK Solutions provides a WhatsApp AI chatbot platform and agent management dashboard for
            businesses. The platform enables automated customer conversations, human agent escalation,
            meeting scheduling, and performance analytics.
          </p>
          <p className="mt-3">
            By accessing or using the WAK Solutions platform — including the dashboard, any connected
            WhatsApp channels, or any associated APIs — you agree to be bound by these Terms &amp;
            Conditions. If you do not agree, you must not use the platform.
          </p>
        </Section>

        {/* 2. WhatsApp Messaging Consent */}
        <Section title={t("termsPageSectionMessaging")} isRtl={isRtl}>
          <p>
            Customers who initiate conversations via a WAK Solutions-connected WhatsApp number consent
            to receiving automated messages generated by the AI chatbot, as well as messages sent by
            human agents through the dashboard.
          </p>
          <p className="mt-3">
            Businesses using WAK Solutions are responsible for ensuring their use of WhatsApp messaging
            complies with WhatsApp&apos;s Business Policy and applicable local communications laws.
            WAK Solutions does not send unsolicited messages on behalf of clients.
          </p>
        </Section>

        {/* 3. Data Usage */}
        <Section title={t("termsPageSectionData")} isRtl={isRtl}>
          <p>
            WAK Solutions stores conversation history, contact information, meeting records, and usage
            data to operate and improve the service. This data is processed on behalf of the business
            client and is not sold to third parties.
          </p>
          <p className="mt-3">
            Stored data may include customer phone numbers, message content, voice note transcriptions,
            survey responses, and agent activity logs. Data is retained for the duration of the service
            agreement and may be deleted upon written request.
          </p>
          <p className="mt-3">
            WAK Solutions takes reasonable technical measures to protect stored data. However, no
            internet-based service can guarantee absolute security.
          </p>
        </Section>

        {/* 4. Agent Responsibilities */}
        <Section title={t("termsPageSectionAgents")} isRtl={isRtl}>
          <p>
            Agents granted access to the WAK Solutions dashboard must keep their login credentials
            secure and must not share them with unauthorised individuals. Agents are responsible for
            all activity performed under their account.
          </p>
          <p className="mt-3">
            Agents must interact with customers professionally and in accordance with the policies of
            the business they represent. Misuse of the dashboard — including sending inappropriate
            messages, accessing data beyond the scope of their role, or attempting to circumvent
            platform controls — may result in account suspension.
          </p>
        </Section>

        {/* 5. Cookie Policy */}
        <Section title={t("termsPageSectionCookies")} isRtl={isRtl}>
          <p>
            The WAK Solutions dashboard uses session cookies for authentication only. A session cookie
            is set when you log in and is used solely to maintain your authenticated session. It is
            removed when you log out or when the session expires.
          </p>
          <p className="mt-3">
            WAK Solutions does not use tracking cookies, advertising cookies, or third-party analytics
            cookies on the dashboard. Public-facing pages (booking, survey) do not use cookies at all.
          </p>
        </Section>

        {/* 6. Service Terms */}
        <Section title={t("termsPageSectionServiceTerms")} isRtl={isRtl}>
          <p>
            WAK Solutions reserves the right to suspend or terminate access to any account that
            violates these Terms &amp; Conditions, without prior notice where necessary to protect the
            platform or other users.
          </p>
          <p className="mt-3">
            The platform is provided on an as-is basis during the current pilot phase. WAK Solutions
            makes no guarantees of specific uptime, availability, or uninterrupted service. Scheduled
            and unscheduled maintenance may occur at any time.
          </p>
          <p className="mt-3">
            WAK Solutions may update these Terms &amp; Conditions at any time. Continued use of the
            platform after an update constitutes acceptance of the revised terms.
          </p>
        </Section>

        {/* 7. Contact */}
        <Section title={t("termsPageSectionContact")} isRtl={isRtl}>
          <p>
            For questions, concerns, or requests related to these Terms &amp; Conditions or your data,
            please contact WAK Solutions via the support email provided to you at the time of
            onboarding. We aim to respond within 2 business days.
          </p>
        </Section>

        {/* Footer */}
        <div className="pt-4 border-t border-white/[0.08] text-center text-sm text-brand-slate">
          {t("termsPageFooter")}
        </div>
      </main>
    </div>
  );
}

function Section({
  title,
  children,
  isRtl,
}: {
  title: string;
  children: React.ReactNode;
  isRtl: boolean;
}) {
  return (
    <section className="bg-brand-navy rounded-xl border border-white/[0.08] px-7 py-6">
      <h2 className="text-lg font-bold text-brand-cyan mb-3 flex items-center gap-2">
        <span className="w-1 h-5 rounded-full bg-brand-blue flex-shrink-0" />
        {title}
      </h2>
      <div className="text-sm text-white/90 leading-relaxed">{children}</div>
    </section>
  );
}
